add-testing: consolidate

diff --git a/src/jobs/helm/test/kubesec.yml b/src/jobs/helm/test/kubesec.yml
--- a/src/jobs/helm/test/kubesec.yml
+++ b/src/jobs/helm/test/kubesec.yml
@@ -50,45 +50,6 @@ steps:
         sudo install kubesec/kubesec /usr/bin/kubesec
         rm -rf kubesec/
   - run:
-      name: 'Pre: define test function'
-      description: Test that the manifests are both valid and meet our minimum scoring requirement across supported Kubernetes versions.
-      command: |+
-        test()
-        {
-            if [ $# -ne 2 ]; then
-                printf "Function \"test\" expected 2 arguments: Helm chart path, Kubernetes version.\\n" >&2
-                exit 1
-            fi
-
-            local chart_path kubernetes_version report results results_length i score
-
-            chart_path="$1"
-            kubernetes_version="$2"
-
-            report="$(helm template "$chart_path" | kubesec scan - --kubernetes-version "$kubernetes_version" --schema-location default << parameters.kubeconform-schema >> || true)"
-            results="$(printf "%s" "$report" | jq -r '{ "results": [ .[] | { "type": .object, "valid": .valid, "score": .score } ] }')"
-            results_length="$(printf "%s" "$results" | jq -r '.results | length')"
-
-            printf "INFO: running kubesec against chart located at \"%s\" K8s v%s\\n" "$chart_path" "$kubernetes_version"
-
-            for (( i=0; i<results_length; i++ )); do
-                # kubeconform: test that the manifest is actually a valid kubernetes manifest for this version of K8s.
-                if [ "$(printf "%s" "$results" | jq -r ".results[$i].valid")" != "true" ]; then
-                    printf "ERROR: manifest \"%s\" on chart \"%s\" is not valid on Kubernetes version \"%s\".\\n" "$(printf "%s" "$results" | jq -r ".results[$i].type")" "$chart_path" "$kubernetes_version" >&2
-                    printf "%s\\n" "$report"
-                    exit 1
-                fi
-
-                # Test that the kubesec score meets our minimum requirement.
-                score="$(printf "%s" "$results" | jq -r ".results[$i].score")"
-                if [ "$score" -lt "<< parameters.minimum-score >>" ]; then
-                    printf "ERROR: manifest \"%s\" on chart \"%s\" does not meet minimum score \"%i\" on Kubernetes version \"%s\".\\n" "$(printf "%s" "$results" | jq -r ".results[$i].type")" "$chart_path" "<< parameters.minimum-score >>" "$kubernetes_version" >&2
-                    printf "%s\\n" "$report"
-                    exit 1
-                fi
-            done
-        }
-  - run:
       name: kubesec
       description: Run kubesec against a variety of Kubernetes versions and charts.
       command: |+
@@ -97,7 +58,27 @@ steps:
 
         for chart_path in "${_HELM_CHART_DIRECTORIES[@]}"; do
             for kubernetes_version in "${_TARGET_KUBERNETES_VERSIONS[@]}"; do
-                printf "kubesec: testing \"%s\" on k8s version \"%s\"" "$chart_path" "$kubernetes_version"
-                test "$chart_path" "$kubernetes_version"
+                printf "kubesec: testing \"%s\" on k8s version \"%s\"\\n" "$chart_path" "$kubernetes_version"
+
+                report="$(helm template "$chart_path" | kubesec scan - --kubernetes-version "$kubernetes_version" --schema-location default << parameters.kubeconform-schema >> || true)"
+                results="$(printf "%s" "$report" | jq -r '{ "results": [ .[] | { "type": .object, "valid": .valid, "score": .score } ] }')"
+                results_length="$(printf "%s" "$results" | jq -r '.results | length')"
+
+                for (( i=0; i<results_length; i++ )); do
+                    # kubeconform: test that the manifest is actually a valid kubernetes manifest for this version of K8s.
+                    if [ "$(printf "%s" "$results" | jq -r ".results[$i].valid")" != "true" ]; then
+                        printf "ERROR: manifest \"%s\" on chart \"%s\" is not valid on Kubernetes version \"%s\".\\n" "$(printf "%s" "$results" | jq -r ".results[$i].type")" "$chart_path" "$kubernetes_version" >&2
+                        printf "%s\\n" "$report"
+                        exit 1
+                    fi
+
+                    # Test that the kubesec score meets our minimum requirement.
+                    score="$(printf "%s" "$results" | jq -r ".results[$i].score")"
+                    if [ "$score" -lt "<< parameters.minimum-score >>" ]; then
+                        printf "ERROR: manifest \"%s\" on chart \"%s\" does not meet minimum score \"%i\" on Kubernetes version \"%s\".\\n" "$(printf "%s" "$results" | jq -r ".results[$i].type")" "$chart_path" "<< parameters.minimum-score >>" "$kubernetes_version" >&2
+                        printf "%s\\n" "$report"
+                        exit 1
+                    fi
+                done
             done
         done
